services:
  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - db
    networks:
      - product
    env_file:
      - ./backend/.env

  db:
    image: postgres:16-alpine
    container_name: database
    volumes:
      - db-data:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env
    networks:
      - product

  frontend:
    build: ./frontend
    container_name: proxy
    ports:
      - "0.0.0.0:80:80"
    networks:
      - product
    depends_on:
      - backend

volumes:
  db-data:

networks:
  product:

