name: trivy_scan

on:
  push:
    branches: [main]
  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: build image backend
        run: docker build -t my-backend ./backend

      - name: build image frontend
        run: docker build -t my-frontend ./frontend

      - name: Scan Backend with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'my-backend:latest'
          format: 'table'
          exit-code: '0'
          severity: 'CRITICAL,HIGH'

      - name: Scan frontend with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'my-frontend:latest'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'
